language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: YCQKZqeN3IoyQn2jEVlBjcykE+uA0sGWko9GQovzr+/VjUg5pSjVdaCpFknbAUBuOAz45ufD+Wxn9kaJTy4X5GQULT8Ykhkvnd+gom0DLriH0EkWQTueEseVwJlqLhva0eDgmjWsTYA3UPZaZKkASC5f7dnTvxISAYbIOmcyJaotLSz054EdvgaXg6keYIBMJTtNq6Dc7F+o6Tz+p0vGJYvFa/0d48IE+67/jAldr93W7CrbB+bzgSbMOTqOPx8Ufwz2jGWfUt93qZ51xflNM6D8hB9hfC/2/ZIAnkfynfEvBuWlBOlQcjTeFTqxYT6jWWboMY30DYVbw5mLht9JjPP3XM/xBq9DO0pgde1E/x4wnBVDO64GIWQoSIgSOz1MEXCJdWMlDjytn4hhgbpWrL9U//I9Rf20J60CuCqT++8JHaqVkiKhtd9AOwFPfAiiSNmmQpDj6PIiBBgLbT1WH1zKklJja4fRPnBj4vOoxFauwARGlAW09nHBgKuZ1BSF0owbK1AlVfPBkrqeGEHBqK6xDBJj7Ty1FiFeFIBx/zLG6q/aN3uQ7cwwAuG4vJA9HRBfW+hIWsDkxhuGBEBHN53CVWWz609d2k37QfEOtKYc0hzyQJsLAor+HDlE4HwSF6IuaTciBjuGNTtO7GLQNe/ZDoxjnFgQNaKjkA3tNF4=
  app: frozen-temple-20849
  on:
    repo: stavdavis/pediatrician-app
