language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Hs6yuj7SIEMqboQI0rfA6uGsgJe+NYBitdf2swYNJggNZHlwZ7NK8/PF23srp9IwCfmPC0OXoYbORt5n8zB+I4q8LL4vS+EAJXNOrxeuVHYRD1aBMdklovOQNoiCoiiVCy/+5kSjmeuDsYjsuvP2TltQDGFt6xnSUS1+aQsSWDmdYMejMINSmfLjRTiwy1ZLLieUb3VwkNK1WfGzYwK4rL7AyKrOg2ykVpsGLBmBmyxr5rUPllNnz15dW3yO1ICOX+0qrxzYc3H8iPy4seump0BlVJT94N4pJsS//kD1DqtZSLz+QZmc2gD1GvjjlB87i4McYBLv8tG465ZmRf4G0k6x5rBNjhgmVN30RTRu2vLG3zTaTueKx5mUgjHYkm0bHwPoJKJnQ/irzqGgRP2CXEvXiz61MpxB2yAs9onXTdKWukyA+l6wCKWtXWwU5viCiU8a1+H6NP0bzw/8S9FWVR482Y+opZSvT9bgsTwEldC2+B+VG1b4Yr8suk97rgC9UnmeACIayGpygIEZAThn6g0FxaTMXwg8i9yLzLQ4mt5GOm6biiotao+V+4TuEDBA5LYCmTIfTDBbD6mwXh3RPG6o0VZuBAKRmOsmshpgPz8VpBTScyk8Zr2LJaaQtuZd1KKQzajOiJZEKp2JIPrWjCeY0EV/QdxGjFv6GqH3Uww=
  app: frozen-temple-20849
  on:
    repo: stavdavis/pediatrician-app
